### ISSUE TITLE
error build from your new distro 2.2

### ISSUE THREAD

**Issue by st7TEAM** [oe-alliance/build-enviroment#2] opened 2014-06-01 15:51 UTC
ERROR: Traceback (most recent call last):
  File "/home/universaldz/Bureau/oe/build-enviroment/bitbake/lib/bb/cookerdata.py", line 163, in wrapped
    return func(fn, *args)
  File "/home/universaldz/Bureau/oe/build-enviroment/bitbake/lib/bb/cookerdata.py", line 173, in parse_config_file
    return bb.parse.handle(fn, data, include)
  File "/home/universaldz/Bureau/oe/build-enviroment/bitbake/lib/bb/parse/**init**.py", line 99, in handle
    return h['handle'](fn, data, include)
  File "/home/universaldz/Bureau/oe/build-enviroment/bitbake/lib/bb/parse/parse_py/ConfHandler.py", line 120, in handle
    abs_fn = resolve_file(fn, data)
  File "/home/universaldz/Bureau/oe/build-enviroment/bitbake/lib/bb/parse/**init**.py", line 122, in resolve_file
    raise IOError("file %s not found" % fn)
IOError: file /home/universaldz/Bureau/oe/build-enviroment/meta-oe-alliance/conf/layer.conf not found

ERROR: Unable to parse /home/universaldz/Bureau/oe/build-enviroment/meta-oe-alliance/conf/layer.conf: file /home/universaldz/Bureau/oe/build-enviroment/meta-oe-alliance/conf/layer.conf not found
make: **\* [image] Error 1

**Comment by janty** [comment] 2014-06-01 19:39
I can confirm, after a fresh 2.2
"git clone git@github.com:oe-alliance/build-enviroment.git"

 MACHINE=evo DISTRO=openatv make image
Generating /home/e2/1-6-14/build-enviroment/builds/openatv/env.source
Generating /home/e2/1-6-14/build-enviroment/builds/openatv/conf/openatv.conf
Generating /home/e2/1-6-14/build-enviroment/builds/openatv/conf/bblayers.conf
ERROR: Traceback (most recent call last):
  File "/home/e2/1-6-14/build-enviroment/bitbake/lib/bb/cookerdata.py", line 163, in wrapped
    return func(fn, *args)
  File "/home/e2/1-6-14/build-enviroment/bitbake/lib/bb/cookerdata.py", line 173, in parse_config_file
    return bb.parse.handle(fn, data, include)
  File "/home/e2/1-6-14/build-enviroment/bitbake/lib/bb/parse/**init**.py", line 99, in handle
    return h['handle'](fn, data, include)
  File "/home/e2/1-6-14/build-enviroment/bitbake/lib/bb/parse/parse_py/ConfHandler.py", line 120, in handle
    abs_fn = resolve_file(fn, data)
  File "/home/e2/1-6-14/build-enviroment/bitbake/lib/bb/parse/**init**.py", line 122, in resolve_file
    raise IOError("file %s not found" % fn)
IOError: file /home/e2/1-6-14/build-enviroment/meta-oe-alliance/conf/layer.conf not found

ERROR: Unable to parse /home/e2/1-6-14/build-enviroment/meta-oe-alliance/conf/layer.conf: file /home/e2/1-6-14/build-enviroment/meta-oe-alliance/conf/layer.conf not found
make: **\* [image] Error 1

**Comment by arn354** [comment] 2014-06-01 19:54
Do you have the correct makefile?
To my knowledge needed makefile is not public yet

**Comment by janty** [comment] 2014-06-01 19:59
i do not use any different makefile other then the one in the fresh build envirioment, I will wait for the experts to the new release of the file.

**Comment by arn354** [comment] 2014-06-01 20:12
You definitly need to replace makefile. The one in cloned build-enviroment is not the correct one.

**Comment by janty** [comment] 2014-06-01 20:24
ok, last correct build versions are the ones from 20-05-2014, but the included makefile cannot be used. The new branch layer is'nt implemented yet. I have to wait because my skills are not enough by far to chance it in a correct way.

**Comment by AbuBaniaz** [comment] 2016-01-22 20:53
Do we close this?

**Closed as completed** 2016-01-22 21:16 UTC
