### ISSUE TITLE
python-wifi build error nextp3 branch 

### ISSUE THREAD

**Issue by zKhadiri** [oe-alliance/build-enviroment#42] opened 2020-08-26 13:43 UTC
```
ERROR: python-wifi-0.8.0-r0 do_configure: Execution of '/home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/temp/run.do_configure.1633489' failed with exit code 2:
/home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/recipe-sysroot-native/usr/bin/python-native/python: can't open file 'setup.py': [Errno 2] No such file or directory
WARNING: /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/temp/run.do_configure.1633489:156 exit 2 from 'NO_FETCH_BUILD=1 /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/recipe-sysroot-native/usr/bin/python-native/python setup.py clean'
WARNING: Backtrace (BB generated script): 
	#1: distutils_do_configure, /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/temp/run.do_configure.1633489, line 156
	#2: do_configure, /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/temp/run.do_configure.1633489, line 150
	#3: main, /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/temp/run.do_configure.1633489, line 162

Backtrace (metadata-relative locations):
	#1: distutils_do_configure, /home/zakaria/oe-alliance/build-enviroment/meta-python2/classes/distutils.bbclass, line 17
	#2: do_configure, autogenerated, line 2
ERROR: Logfile of failure stored in: /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/temp/log.do_configure.1633489
Log data follows:
| DEBUG: Executing shell function do_configure
| /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/recipe-sysroot-native/usr/bin/python-native/python: can't open file 'setup.py': [Errno 2] No such file or directory
| WARNING: /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/temp/run.do_configure.1633489:156 exit 2 from 'NO_FETCH_BUILD=1 /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/recipe-sysroot-native/usr/bin/python-native/python setup.py clean'
| WARNING: Backtrace (BB generated script):
| 	#1: distutils_do_configure, /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/temp/run.do_configure.1633489, line 156
| 	#2: do_configure, /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/temp/run.do_configure.1633489, line 150
| 	#3: main, /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/temp/run.do_configure.1633489, line 162
| ERROR: Execution of '/home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/temp/run.do_configure.1633489' failed with exit code 2:
| /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/recipe-sysroot-native/usr/bin/python-native/python: can't open file 'setup.py': [Errno 2] No such file or directory
| WARNING: /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/temp/run.do_configure.1633489:156 exit 2 from 'NO_FETCH_BUILD=1 /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/recipe-sysroot-native/usr/bin/python-native/python setup.py clean'
| WARNING: Backtrace (BB generated script):
| 	#1: distutils_do_configure, /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/temp/run.do_configure.1633489, line 156
| 	#2: do_configure, /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/temp/run.do_configure.1633489, line 150
| 	#3: main, /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp/work/cortexa15hf-neon-vfpv4-oe-linux-gnueabi/python-wifi/0.8.0-r0/temp/run.do_configure.1633489, line 162
| 
| Backtrace (metadata-relative locations):
| 	#1: distutils_do_configure, /home/zakaria/oe-alliance/build-enviroment/meta-python2/classes/distutils.bbclass, line 17
| 	#2: do_configure, autogenerated, line 2
ERROR: Task (/home/zakaria/oe-alliance/build-enviroment/meta-oe-alliance/meta-oe/recipes-devtools/python/python-wifi_0.8.0.bb:do_configure) failed with exit code '1'
NOTE: Tasks Summary: Attempted 1828 tasks of which 1816 didn't need to be rerun and 1 failed.

Summary: 1 task failed:
  /home/zakaria/oe-alliance/build-enviroment/meta-oe-alliance/meta-oe/recipes-devtools/python/python-wifi_0.8.0.bb:do_configure
Summary: There was 1 WARNING message shown.
Summary: There was 1 ERROR message shown, returning a non-zero exit code.
make: *** [Makefile:996: image] Error 1

```

**Comment by nickersk** [comment] 2020-08-26 14:11
hi, i cant reproduce this error. try to wipe out /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp directory and re-run build.

**Comment by zKhadiri** [comment] 2020-08-26 14:23
> hi, i cant reproduce this error. try to wipe out /home/zakaria/oe-alliance/build-enviroment/builds/openatv/release/sf8008/tmp directory and re-run build.

yeah i already cleared the tmp file but the same result i keep getting this build error 
i have one question can i build atv6.5 with python 2.7.18 on this branch ?

**Comment by zKhadiri** [comment] 2020-08-26 14:26
should i uncomment this lines 

`PYTHON_BASEVERSION ?= "2.7"
PREFERRED_VERSION_python ?= "2.7.18"
PREFERRED_VERSION_python-native ?= "2.7.18"
PYTHON_PN = "python"`

**Comment by nickersk** [comment] 2020-08-26 14:32
try to switch your local python to python3. on ubuntu run:
sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 2
check if python3 is selected by this command: sudo update-alternatives --config python

**Comment by zKhadiri** [comment] 2020-08-26 15:27
> try to switch your local python to python3. on ubuntu run:
> sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
> sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 2
> check if python3 is selected by this command: sudo update-alternatives --config python

i got the same error again

**Comment by zKhadiri** [comment] 2020-08-26 15:31
i dont know why the log say's that setup file is not found

`can't open file 'setup.py': [Errno 2] No such file or directory`

![Screenshot from 2020-08-26 15-31-21](https://user-images.githubusercontent.com/43075184/91324135-3dc88300-e7b1-11ea-9752-8ee1cecde778.png)

**Comment by nickersk** [comment] 2020-08-26 15:44
try to add S = "${WORKDIR}/git" to meta-oe-alliance/meta-oe/recipes-devtools/python/python-wifi_0.8.0.bb and run build

**Comment by zKhadiri** [comment] 2020-08-26 15:51
> try to add S = "${WORKDIR}/git" to meta-oe-alliance/meta-oe/recipes-devtools/python/python-wifi_0.8.0.bb and run build

thanks , everything is fine now

**Comment by nickersk** [comment] 2020-08-26 16:50
solved, closing.

**Closed as completed by nickersk** 2020-08-26 16:50 UTC
